version: "3"

volumes:
  go-modules: # Define a volume for Go modules

services:
  integration_tests:
    image: ethereumoptimism/builder:latest
    volumes:
      - ./:/mnt
    env_file:
      - docker-compose.env
    working_dir: /mnt/integration-tests
    entrypoint: ["sh", "-c", "yarn && yarn build"]

  geth_l2:
    image: ethereumoptimism/builder:latest
    volumes:
      - ./:/mnt
      - go-modules:/go/pkg/mod # Put modules cache into a separate volume
    env_file:
      - docker-compose.env
    ports:
      - 8545:8545
    entrypoint: ["make", "geth"]
    working_dir: /mnt/go-ethereum

  batch_submitter:
    image: ethereumoptimism/builder:latest
    env_file:
      - docker-compose.env
    volumes:
      - ./:/mnt
    working_dir: /mnt/optimism-monorepo
    entrypoint: ["sh", "-c", "yarn && yarn build"]
