version: "3"

services:
  deployer:
    image: ethereumoptimism/deployer:${DEPLOYER_TAG:-latest}
    working_dir: /contracts
    entrypoint: ["/opt/wait-for-l1.sh", "yarn", "run", "--silent", "deploy"]
    volumes:
      - ./contracts:/contracts
    ports:
      - 8080:8080
