version: "3"

services:

  message_relayer:
    image: ethereumoptimism/message-relayer:${MESSAGE_RELAYER_TAG:-latest}
    env_file:
      - docker-compose.env
    environment:
      # The key is seeded with eth by hardhat
      - L1_WALLET_KEY=0xea8b000efb33c49d819e8d6452f681eed55cdf7de47d655887fc0e318906f2e7

