version: "3"

services:
  message_relayer:
    image: ethereumoptimism/message-relayer:${MESSAGE_RELAYER_TAG:-latest}
    environment:
      - L1_WALLET_KEY=0xea8b000efb33c49d819e8d6452f681eed55cdf7de47d655887fc0e318906f2e7
      - L1_NODE_WEB3_URL=http://l1_chain:9545
      - L2_NODE_WEB3_URL=http://geth_l2:8545
      - DEPLOYER_HTTP=http://deployer:8080
      - ADDRESS_MANAGER_ADDRESS=
